### ISSUE TITLE
About dataset_splits.zip

### ISSUE THREAD

**Issue by xiexiaodonger** [AnasEmad11/CLAP#4]
Hello,

I am very pleased to see such excellent work, but I have some questions regarding the dataset partitioning. In the file event_video_num_partition_13_V3.pkl, each video is assigned an index. However, the video with index 0 in event_partition_13_V3.pkl has 55 features, which corresponds to 55 video segments. I have calculated that each video segment contains 16 frames, so the duration of the video with index 0 is 29 seconds. This does not match the duration of Abuse/Abuse001_x264.mp4. Therefore, I would like to ask about the correspondence between the video index numbers and the original video file names.

Thank you and looking forward to your response!

Best regards,

**Comment by AnasEmad11** [comment]
Hello,

Thanks for the feedback.

The features/segments in question are directly taken from the RTFM repo github.com/tianyu0207/RTFM. I realized that the video with index 0 is  **/Abuse002_x264_i3d** which has 55 features. Abuse/Abuse001_x264.mp4 has been skipped which is a mistake on our part. I will fix it soon. This wouldn't affect the data pre-processing step. You can edit the /list/[UCF_Train_ten_crop_i3d_complete_V1.txt file and generate the new dataset splits. However, you should also concatenate the feature file to the full dataset. 

Thanks.
